USE sakila;

SELECT 	CUSTOMER.FIRST_NAME,
		CUSTOMER.LAST_NAME,
        CUSTOMER.EMAIL,
		COUNTRY.COUNTRY

FROM CUSTOMER
LEFT JOIN ADDRESS ON CUSTOMER.ADDRESS_ID = ADDRESS.ADDRESS_ID
LEFT JOIN CITY ON ADDRESS.CITY_ID = CITY.CITY_ID
LEFT JOIN COUNTRY ON CITY.COUNTRY_ID = COUNTRY.COUNTRY_ID

WHERE COUNTRY = 'CANADA';

				
