USE sakila;

SELECT 	STORE.STORE_ID,
		COUNTRY.COUNTRY,
        CITY.CITY
		
        
FROM STORE
LEFT JOIN ADDRESS ON STORE.ADDRESS_ID = ADDRESS.ADDRESS_ID
LEFT JOIN CITY ON ADDRESS.CITY_ID = CITY.CITY_ID
LEFT JOIN COUNTRY ON CITY.COUNTRY_ID = COUNTRY. COUNTRY_ID;


-- GROUP BY STORE_ID;


				
