USE sakila;

SELECT 	STAFF.FIRST_NAME,
		STAFF.LAST_NAME,
        -- STAFF.ADDRESS_ID,
        ADDRESS.ADDRESS_ID
        
FROM STAFF 
LEFT JOIN ADDRESS  ON STAFF.ADDRESS_ID = ADDRESS.ADDRESS_ID  ;      

		
		