USE sakila;

SELECT 	CATEGORY.NAME,
		-- CATEGORY.CATEGORY_ID,
        -- FILM_CATEGORY.FILM_ID,
        FILM_TEXT.TITLE
        
FROM CATEGORY
LEFT JOIN FILM_CATEGORY ON CATEGORY.CATEGORY_ID = FILM_CATEGORY.CATEGORY_ID
LEFT JOIN FILM_TEXT ON FILM_CATEGORY.FILM_ID = FILM_TEXT.FILM_ID


WHERE CATEGORY.NAME = 'FAMILY';

				
